version: '3.7'

services:
    nginx:
        build:
            context: ./docker/nginx
            args:
                DOCKER_ENV: "dev"
        ports:
            - "80:80"
        volumes:
            - ./logs/nginx:/var/log/nginx:cached
            - ./app:/var/www/app:cached
    php:
        build: ./docker/php
        image: lizai-php:latest
        volumes: &php_volumes
            - ./app:/var/www/app:cached
            - ./logs/app:/var/www/app/var/log:cached
        environment:
            REDIS_HOST: redis
            REDIS_PORT: 6379
    redis:
        image: redis:4-alpine
    node:
        image: node:13.12.0-alpine
        working_dir: /var/www/app/node
        volumes:
            - ./app:/var/www/app
            - ./app:/bindmount:rw
        ports:
            - "8080:8080"
    db:
        image: mariadb:10.4.8
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: vertriebsportal
            MYSQL_USER: vertriebsportal
            MYSQL_PASSWORD: vertriebsportal